name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Use the svg-only version as requested
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Customize the SVG
      - name: Customize SVG
        run: |
          sed -i 's/fill="#9f9f9f"/fill="#FF5733"/g' dist/github-contribution-grid-snake.svg
          sed -i 's/text="snake"/text="UltraBpro"/g' dist/github-contribution-grid-snake.svg
          sed -i 's/stroke-width="0.5"/stroke-width="0.2"/g' dist/github-contribution-grid-snake.svg
          sed -i 's/stroke="#333"/stroke="#000"/g' dist/github-contribution-grid-snake.svg

      # Push to the output branch
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
